force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizzes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Published?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quiz__c/fields/Quiz_Category__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Category__c</fullName>
    <label>Quiz Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuizCategory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/Quiz_Answer__c.object-meta.xml
<CustomObject>
    <label>Quiz Answer</label>
    <nameField>
        <displayFormat>QA-{00000000}</displayFormat>
        <label>Quiz Answer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Answer__c/fields/Answer_Text__c.field-meta.xml
<CustomField>
    <fullName>Answer_Text__c</fullName>
    <label>Answer Text</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quiz_Answer__c/fields/Quiz_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Line_Item__c</fullName>
    <label>Quiz Line Item</label>
    <referenceTo>Quiz_Line_Item__c</referenceTo>
    <relationshipLabel>Quiz Answers</relationshipLabel>
    <relationshipName>Quiz_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quiz_Line_Item__c/Quiz_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quiz Line Item</label>
    <nameField>
        <displayFormat>QLI-{00000000}</displayFormat>
        <label>Quiz Line Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quiz Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Line_Item__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Correct Answer</label>
    <referenceTo>Quiz_Answer__c</referenceTo>
    <relationshipLabel>Quiz Line Items</relationshipLabel>
    <relationshipName>Quiz_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quiz_Line_Item__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <label>Quiz</label>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>Quiz Line Items</relationshipLabel>
    <relationshipName>Quiz_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuizFin.cls
public class QuizFin {
	@AuraEnabled(cacheable=true)
    public static List<QuizWrapper> getQuizData() {
        List<QuizWrapper> qWrapper = new List<QuizWrapper>();
        for(Quiz__c q : [SELECT Id, Name, Quiz_Category__c, Published__c,
                        (SELECT Id, Question__c, Correct_Answer__c FROM Quiz_Line_Items__r)
                        FROM Quiz__c
                        WHERE Published__c = true]) {
            QuizWrapper qw = new QuizWrapper();
            qw.Id = q.Id;
            qw.name = q.Name;
            qw.category = q.Quiz_Category__c;
            qw.published = q.Published__c;
            qw.quizli = getQuizLineItems(q.Quiz_Line_Items__r);
            qWrapper.add(qw);
        }

        return qWrapper;
    }

    private static List<QuizLineItem> getQuizLineItems(List<Quiz_Line_Item__c> quizlis) {
        List<QuizLineItem> quizLineItems = new List<QuizLineItem>();
        for(Quiz_Line_Item__c qli: quizlis) {
            QuizLineItem qLineItem = new QuizLineItem();
            qLineItem.question = qli.Question__c;
            qLineItem.correctAnswer = qli.Correct_Answer__c;
            qLineItem.quizAnswer = getQuizAnswers(qli.Id);
            quizLineItems.add(qLineItem);
        }

        return quizLineItems;
    }

    private static List<QuizAnswer> getQuizAnswers(ID quizLineItemId) {
        List<QuizAnswer> quizAnswers = new List<QuizAnswer>();
        for(Quiz_Answer__c qa: [SELECT Id, Answer_Text__c 
                                FROM Quiz_Answer__c
                                WHERE Quiz_Line_Item__c = :quizLineItemId]) {
            QuizAnswer qAnswer = new QuizAnswer();
            qAnswer.answerText = qa.Answer_Text__c;
            qAnswer.Id = qa.Id;
            quizAnswers.add(qAnswer);
        }

        return quizAnswers;
    }
    
    public class QuizWrapper {
        @AuraEnabled
        public ID Id {get;set;}
        @AuraEnabled
        public String name {get;set;}
        @AuraEnabled
        public String category {get;set;}
        @AuraEnabled
        public Boolean published {get;set;}
        @AuraEnabled
        public List<QuizLineItem> quizli {get;set;}
    }
    
    public class QuizLineItem {
        @AuraEnabled
        public String question {get;set;}
        @AuraEnabled
        public ID correctAnswer {get;set;}
        @AuraEnabled
        public List<QuizAnswer> quizAnswer {get;set;}
    }
    
    public class QuizAnswer {
        @AuraEnabled
        public String answerText {get;set;}
        @AuraEnabled
        public ID Id {get;set;}
    }
}