force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizzes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/fields/Quiz_Category__c.field-meta.xml
<CustomField>
    <fullName>Quiz_Category__c</fullName>
    <label>Quiz Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuizCategory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quiz_Attendee__c/Quiz_Attendee__c.object-meta.xml
<CustomObject>
    <label>Quiz Attendee</label>
    <nameField>
        <label>Quiz Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Attendee__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quiz Attendees</relationshipLabel>
    <relationshipName>Quiz_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quiz_Attendee__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <label>Quiz</label>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>Quiz Attendees</relationshipLabel>
    <relationshipName>Quiz_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuizFinRecordManagerTest.cls
@isTest public class QuizFinRecordManagerTest {

    @isTest static void should_create_contact() {
        String lastname = 'Test1';
        
        Contact newCon;
        Test.startTest();
        newCon = QuizFinRecordManager.createContact(lastname);
        Test.stopTest();
        
        System.assertEquals(lastname, newCon.Name, 'Last name should now be Name of the created contact');
        
    }
    
    @isTest static void should_get_contact() {
        Contact testCon = new Contact(LastName = 'Test1');
        insert testCon;
        
        Contact newCon;
        Test.startTest();
        newCon = QuizFinRecordManager.getContact(testCon.LastName);
        Test.stopTest();
        
        System.assertEquals(testCon.LastName, newCon.Name, 'should get the same contact');
    }
    
    @isTest static void should_create_attendee() {
        Contact con1 = new Contact(LastName = 'Test1');
        insert con1;
        Quiz__c q = new Quiz__c(Name = 'Test Quiz', Quiz_Category__c = 'Movie');
        insert q;
        
        Test.startTest();
        QuizFinRecordManager.createAttendee(1, 2, con1.Id, q.Id);
        Test.stopTest();
        
        List<Quiz_Attendee__c> qas = [SELECT Id FROM Quiz_Attendee__c WHERE Quiz__c = :q.Id AND Player__c = :con1.Id];
        System.assertEquals(1, qas.size(), 'should have one quiz attendee record');
    }
}