force-app/main/default/objects/Contact/fields/Overall_Quiz_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Quiz_Score__c</fullName>
    <formula>Num_of_Quiz_Correct_Responses__c  /  Num_of_Quiz_Questions_Attended__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Overall Quiz Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Quiz</label>
    <nameField>
        <label>Quiz Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quizzes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/fields/Number_of_Questions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Questions__c</fullName>
    <label>Number of Questions</label>
    <summaryForeignKey>Quiz_Line_Item__c.Quiz__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quiz_Attendee__c/Quiz_Attendee__c.object-meta.xml
<CustomObject>
    <label>Quiz Attendee</label>
    <nameField>
        <label>Quiz Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quiz Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz_Attendee__c/fields/Correct_Responses__c.field-meta.xml
<CustomField>
    <fullName>Correct_Responses__c</fullName>
    <label>Correct Responses</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz_Attendee__c/fields/Number_of_Questions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Questions__c</fullName>
    <label>Number of Questions</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quiz_Attendee__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quiz Attendees</relationshipLabel>
    <relationshipName>Quiz_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quiz_Attendee__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <label>Quiz</label>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>Quiz Attendees</relationshipLabel>
    <relationshipName>Quiz_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuizFinRecordManager.cls
public with sharing class QuizFinRecordManager {
	@AuraEnabled(cacheable=false)
    public static Contact createContact(String lastname) {
        Contact newCont = new Contact(LastName=lastname);
        insert newCont;
        
        List<Contact> cons = getContactRecord(lastname);
        
        return !cons.isEmpty() ? cons[0] : null;
    }
    
    @AuraEnabled(cacheable=true)
    public static Contact getContact(String lastname) {
        List<Contact> cons = getContactRecord(lastname);
        return !cons.isEmpty() ? cons[0] : null;
    }
    
    @AuraEnabled(cacheable=false)
    public static void createAttendee(Integer correctResponses, Integer numQuestions, ID contactId, ID quizId) {
        List<Quiz_Attendee__c> qaExists = [SELECT Id FROM Quiz_Attendee__c WHERE Quiz__c = :quizId AND Player__c = :contactId];
        if(!qaExists.isEmpty()) return;
        
        Quiz_Attendee__c qa = new Quiz_Attendee__c(
        	Player__c = contactId,
            Quiz__c = quizId,
            Correct_Responses__c = correctResponses,
            Number_of_Questions__c = numQuestions
        );
        
        insert qa;
    }
    
    private static List<Contact> getContactRecord(String lastname) {
        return [SELECT Id, Name, Overall_Quiz_Score__c FROM Contact WHERE LastName = :lastname];
    }
}